name: Asusxpress CI/CD with Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

  deploy-main:
    runs-on: ubuntu-latest

    needs: build

    if: github.ref == 'refs/heads/main'  # Only run for the main branch

    steps:
      - name: Deploy to Ubuntu server (main)
        uses: appleboy/ssh-action@master
        with:
          host: 54.175.27.249
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/asusxpress
            git pull origin main
            composer install
            php artisan migrate --force

